CREATE VIEW PROPERTY_DETAILS AS
SELECT
    cu.CONDO_ID,
    l.LOCATION_NUM,
    l.LOCATION_NAME,
    l.ADDRESS AS LOCATION_ADDRESS,
    l.CITY AS LOCATION_CITY,
    l.STATE AS LOCATION_STATE,
    l.POSTAL_CODE AS LOCATION_POSTAL_CODE,
    cu.UNIT_NUM,
    cu.SQR_FT,
    cu.BDRMS,
    cu.BATHS,
    cu.CONDO_FEE AS BASE_WEEKLY_RATE
FROM
    CONDO_UNIT cu
JOIN
    LOCATION l ON cu.LOCATION_NUM = l.LOCATION_NUM;
