SELECT 
    C.CUSTOMER_NUM AS PARTICIPANT_NUMBER,
    C.LAST_NAME,
    C.FIRST_NAME,
    T.TRIP_ID AS CLASS_NUMBER,
    T.TRIP_NAME AS CLASS_DESCRIPTION,
    R.TRIP_DATE AS CLASS_DATE
FROM 
    CUSTOMER C
JOIN 
    RESERVATION R ON C.CUSTOMER_NUM = R.CUSTOMER_NUM
JOIN 
    TRIP T ON R.TRIP_ID = T.TRIP_ID;
