CREATE TABLE RENTER (
    RENTER_ID DECIMAL(5,0) PRIMARY KEY,
    FIRST_NAME VARCHAR2(25),
    MIDDLE_INITIAL CHAR(1),
    LAST_NAME VARCHAR2(25),
    ADDRESS VARCHAR2(50),
    CITY VARCHAR2(25),
    STATE CHAR(2),
    POSTAL_CODE CHAR(10),
    TELEPHONE VARCHAR2(15),
    EMAIL VARCHAR2(50)
);
