CREATE TABLE RENTAL_AGREEMENT (
    AGREEMENT_ID DECIMAL(6,0) PRIMARY KEY,
    RENTER_ID DECIMAL(5,0),
    CONDO_ID DECIMAL(4,0),
    START_DATE DATE,
    END_DATE DATE,
    WEEKLY_RENTAL_AMOUNT DECIMAL(7,2),
    FOREIGN KEY (RENTER_ID) REFERENCES RENTER(RENTER_ID),
    FOREIGN KEY (CONDO_ID) REFERENCES CONDO_UNIT(CONDO_ID)
);
